stages:
  - lint
  - build
  - test
  - deploy


build maven:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}/my_maven:${CI_COMMIT_REF_SLUG} -f my-maven .
    - docker push ${CI_REGISTRY_IMAGE}/my_maven:${CI_COMMIT_REF_SLUG}
  tags:
    - gitlab-org-docker
  only:
    changes:
      - pom.xml


build spring:
  image: docker:stable
  stage: build
  needs:
    - job: build maven
      optional: true
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build --build-arg my_maven=${CI_REGISTRY_IMAGE}/my_maven:${CI_COMMIT_REF_SLUG} 
                   -t ${CI_REGISTRY_IMAGE}/spring:${CI_COMMIT_REF_SLUG} .
    - docker push ${CI_REGISTRY_IMAGE}/spring:${CI_COMMIT_REF_SLUG}
  tags:
    - gitlab-org-docker
  only:
    changes:
      - src/**/*
      - pom.xml

deploy to prod:
  stage: deploy
  needs:
    - job: build spring
      optional: true
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY_IMAGE}/spring:${CI_COMMIT_REF_SLUG}
    - docker rm -f ${CI_PROJECT_NAME} || true
    - docker run -d --name ${CI_PROJECT_NAME} -p 80:8080 ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  tags:
    - deploy

