stages:
  - lint
  - build
  - test
  - deploy

default:
  before_script:
    - docker info


build docker:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t optics:latest . #${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} .
    - docker push optics:latest #${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  tags:
    - docker-2
#    - gitlab-org-docker


deploy to prod:
  stage: deploy
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull optics:latest # ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    - docker rm -f ${CI_PROJECT_NAME} || true
    - docker run -d --name ${CI_PROJECT_NAME} -p 80:8080 optics:latest # ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  tags:
    - docker-2