package com.app.optics.models;

public enum AppState {
    PRODUCTS,
    CUSTOMERS,
    NEW_CUSTOMER,
    NEW_RECIPE,
    OLD_RECIPE,
    NEW_LENSES,
    NEW_OTHER,
    EDIT_PRODUCT,
    CHOOSE_OPTION,
    NEW_OPTION,
    CUSTOMER_FROM_RECIPE,
    NOT_FOUND,
    UPLOAD,
    SEND_MESSAGE,
    PRODUCT_MESSAGES,
    HISTORY_MESSAGES,
    MESSAGE_PANEL
}
